const { SYSTEM_PROMPT, INTENT_EXTRACTION_PROMPT, TASK_GENERATION_PROMPT } = require('./system');
const { LINKEDIN_INTENT_PROMPT, NOTION_INTENT_PROMPT, HUBSPOT_INTENT_PROMPT, UPWORK_INTENT_PROMPT } = require('./intents');
const { MULTI_STEP_TASK_PROMPT, BATCH_OPERATION_PROMPT, WORKFLOW_TEMPLATE_PROMPT } = require('./tasks');

module.exports = {
  SYSTEM_PROMPT,
  INTENT_EXTRACTION_PROMPT,
  TASK_GENERATION_PROMPT,

  LINKEDIN_INTENT_PROMPT,
  NOTION_INTENT_PROMPT,
  HUBSPOT_INTENT_PROMPT,
  UPWORK_INTENT_PROMPT,

  MULTI_STEP_TASK_PROMPT,
  BATCH_OPERATION_PROMPT,
  WORKFLOW_TEMPLATE_PROMPT,
};
